export enum Permission {
  // ─── MASTER SETUP ───────────────────────────
  COMPANY_VIEW = 'COMPANY_VIEW',
  COMPANY_CREATE = 'COMPANY_CREATE',
  COMPANY_EDIT = 'COMPANY_EDIT',

  PLANT_VIEW = 'PLANT_VIEW',
  PLANT_CREATE = 'PLANT_CREATE',
  PLANT_EDIT = 'PLANT_EDIT',

  UNIT_VIEW = 'UNIT_VIEW',
  UNIT_CREATE = 'UNIT_CREATE',
  UNIT_EDIT = 'UNIT_EDIT',

  DEPARTMENT_VIEW = 'DEPARTMENT_VIEW',
  DEPARTMENT_CREATE = 'DEPARTMENT_CREATE',
  DEPARTMENT_EDIT = 'DEPARTMENT_EDIT',

  BRANCH_VIEW = 'BRANCH_VIEW',
  BRANCH_CREATE = 'BRANCH_CREATE',
  BRANCH_EDIT = 'BRANCH_EDIT',

  FINANCIAL_YEAR_VIEW = 'FINANCIAL_YEAR_VIEW',
  FINANCIAL_YEAR_CREATE = 'FINANCIAL_YEAR_CREATE',
  FINANCIAL_YEAR_MANAGE = 'FINANCIAL_YEAR_MANAGE',

  // ─── USER MANAGEMENT ────────────────────────
  USER_VIEW = 'USER_VIEW',
  USER_CREATE = 'USER_CREATE',
  USER_EDIT = 'USER_EDIT',
  USER_TOGGLE_STATUS = 'USER_TOGGLE_STATUS',
  USER_RESET_PASSWORD = 'USER_RESET_PASSWORD',
  USER_UNLOCK = 'USER_UNLOCK',

  // ─── PURCHASE ───────────────────────────────
  PURCHASE_VIEW = 'PURCHASE_VIEW',
  PURCHASE_CREATE = 'PURCHASE_CREATE',
  PURCHASE_EDIT = 'PURCHASE_EDIT',
  PURCHASE_APPROVE = 'PURCHASE_APPROVE',

  // ─── INVENTORY ──────────────────────────────
  INVENTORY_VIEW = 'INVENTORY_VIEW',
  INVENTORY_CREATE = 'INVENTORY_CREATE',
  INVENTORY_EDIT = 'INVENTORY_EDIT',

  // ─── PRODUCTION ─────────────────────────────
  PRODUCTION_VIEW = 'PRODUCTION_VIEW',
  PRODUCTION_CREATE = 'PRODUCTION_CREATE',
  PRODUCTION_EDIT = 'PRODUCTION_EDIT',

  // ─── QUALITY ────────────────────────────────
  QUALITY_VIEW = 'QUALITY_VIEW',
  QUALITY_CREATE = 'QUALITY_CREATE',
  QUALITY_EDIT = 'QUALITY_EDIT',

  // ─── FINANCE ────────────────────────────────
  FINANCE_VIEW = 'FINANCE_VIEW',
  FINANCE_CREATE = 'FINANCE_CREATE',
  FINANCE_EDIT = 'FINANCE_EDIT',
  FINANCE_APPROVE = 'FINANCE_APPROVE',

  // ─── VENDORS ────────────────────────────────
  VENDORS_VIEW = 'VENDORS_VIEW',
  VENDORS_CREATE = 'VENDORS_CREATE',
  VENDORS_EDIT = 'VENDORS_EDIT',
  VENDORS_DELETE = 'VENDORS_DELETE',
  // ─── REPORTS ────────────────────────────────
  REPORTS_VIEW = 'REPORTS_VIEW',
  REPORTS_EXPORT = 'REPORTS_EXPORT',

  // ─── SETTINGS ───────────────────────────────
  SETTINGS_VIEW = 'SETTINGS_VIEW',
  SETTINGS_MANAGE = 'SETTINGS_MANAGE',

  // ─── AUDIT ──────────────────────────────────
  AUDIT_VIEW = 'AUDIT_VIEW',
}
