ALTER TABLE "work_orders" ADD COLUMN "cumulativeInputQty" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "work_orders" ADD COLUMN "cumulativeProcessedQty" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "work_orders" ADD COLUMN "cumulativeHandoverQty" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "work_orders" ADD COLUMN "stageStatus" TEXT NOT NULL DEFAULT 'NOT_READY';
