ALTER TABLE "production_qc" ADD COLUMN "acceptedQty" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "production_qc" ADD COLUMN "reworkQty" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "production_qc" ADD COLUMN "holdQty" INTEGER NOT NULL DEFAULT 0;
