BEGIN;
UPDATE users SET "isActive" = false, "updatedAt" = now() WHERE role IN ('PRODUCTION_HEAD','PLANNING_MANAGER','UNIT_HEAD','OPERATOR','VIEWER') AND "companyId" = '83eda866-ba63-472c-902f-561f05b6b1c1';
UPDATE roles SET "isActive" = false, "updatedAt" = now() WHERE name IN ('CORPORATE_ADMIN','GAURD','FINANCE_MANAGER','STORE_MANAGER','PURCHASE_MANAGER','QC_MANAGER','PLANT_HEAD','SUPERVISOR','HR_MANAGER','PRODUCTION_HEAD','PLANNING_MANAGER','UNIT_HEAD','OPERATOR','VIEWER') AND "companyId" = '83eda866-ba63-472c-902f-561f05b6b1c1';
COMMIT;
