import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
// eslint-disable-next-line @typescript-eslint/no-var-requires
const PDFDocument = require('pdfkit');

@Injectable()
export class PdfEngineService {
  constructor(private prisma: PrismaService) {}

  private createDoc(): PDFKit.PDFDocument {
    return new PDFDocument({ margin: 40, size: 'A4' });
  }

  private addHeader(doc: any, title: string, number: string, date: string, companyName = 'Company Name Not Configured') {
    // Company name
    doc.fontSize(18).font('Helvetica-Bold').fillColor('#1e40af').text(companyName, 40, 40);
    doc.fontSize(9).font('Helvetica').fillColor('#6b7280').text('Smart Manufacturing ERP | GSTIN: 29XXXXX1234Z1ZX', 40, 62);

    // Title + number
    doc.fontSize(14).font('Helvetica-Bold').fillColor('#111827').text(title, 40, 90);
    doc.fontSize(10).font('Helvetica').fillColor('#374151').text(`${number} | Date: ${date}`, 40, 108);

    // Horizontal line
    doc.moveTo(40, 125).lineTo(555, 125).strokeColor('#d1d5db').lineWidth(1).stroke();
    return 140; // return next Y position
  }

  private addFooter(doc: any, companyName = 'this ERP system') {
    const pageHeight = doc.page.height;
    doc.moveTo(40, pageHeight - 50).lineTo(555, pageHeight - 50).strokeColor('#d1d5db').lineWidth(0.5).stroke();
    doc.fontSize(8).font('Helvetica').fillColor('#9ca3af')
      .text(`Generated by ${companyName} | Confidential`, 40, pageHeight - 40, { align: 'center' });
  }

  private addTwoCol(doc: any, y: number, left: {[key:string]:string}, right: {[key:string]:string}) {
    let leftY = y;
    let rightY = y;
    Object.entries(left).forEach(([k, v]) => {
      doc.fontSize(8).font('Helvetica-Bold').fillColor('#6b7280').text(k, 40, leftY);
      doc.fontSize(9).font('Helvetica').fillColor('#111827').text(v || '—', 40, leftY + 11);
      leftY += 28;
    });
    Object.entries(right).forEach(([k, v]) => {
      doc.fontSize(8).font('Helvetica-Bold').fillColor('#6b7280').text(k, 300, rightY);
      doc.fontSize(9).font('Helvetica').fillColor('#111827').text(v || '—', 300, rightY + 11);
      rightY += 28;
    });
    return Math.max(leftY, rightY) + 10;
  }

  private addTableHeader(doc: any, y: number, cols: {text:string, x:number, width:number}[]) {
    doc.rect(40, y, 515, 20).fillColor('#1e40af').fill();
    cols.forEach(col => {
      doc.fontSize(8).font('Helvetica-Bold').fillColor('#ffffff').text(col.text, col.x, y + 6, { width: col.width });
    });
    return y + 20;
  }

  private addTableRow(doc: any, y: number, cols: {text:string, x:number, width:number}[], shade: boolean) {
    if (shade) doc.rect(40, y, 515, 18).fillColor('#f9fafb').fill();
    doc.rect(40, y, 515, 18).strokeColor('#e5e7eb').lineWidth(0.5).stroke();
    cols.forEach(col => {
      doc.fontSize(8).font('Helvetica').fillColor('#111827').text(col.text, col.x + 2, y + 5, { width: col.width - 4 });
    });
    return y + 18;
  }

  private addSummaryBox(doc: any, y: number, rows: {label:string, value:string, bold?:boolean}[]) {
    const boxX = 350;
    let boxY = y + 10;
    doc.rect(boxX, boxY - 5, 205, rows.length * 20 + 10).strokeColor('#d1d5db').lineWidth(0.5).stroke();
    rows.forEach(row => {
      doc.fontSize(8).font(row.bold ? 'Helvetica-Bold' : 'Helvetica')
        .fillColor(row.bold ? '#111827' : '#374151')
        .text(row.label, boxX + 5, boxY)
        .text(row.value, boxX + 105, boxY, { width: 95, align: 'right' });
      boxY += 20;
    });
    return boxY + 10;
  }

  async generatePurchaseOrderPdf(id: string, companyId: string): Promise<Buffer> {
    const po = await this.prisma.purchaseOrder.findFirst({
      where: { id, companyId },
      include: { vendor: true, items: true, company: true },
    });
    if (!po) throw new NotFoundException('Purchase Order not found');

    const doc = this.createDoc();
    const chunks: Buffer[] = [];
    doc.on('data', chunk => chunks.push(chunk));

    const fmtDate = (d: any) => d ? new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';
    const fmt = (n: any) => `Rs. ${Number(n || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`;

    let y = this.addHeader(doc, 'PURCHASE ORDER', po.poNumber, fmtDate(po.poDate), po.company?.name);

    y = this.addTwoCol(doc, y, {
      'Vendor': po.vendor?.name || '—',
      'Vendor Code': po.vendor?.code || '—',
      'Phone': po.vendor?.phone || '—',
    }, {
      'PO Date': fmtDate(po.poDate),
      'Delivery Date': fmtDate(po.deliveryDate),
      'Status': po.status,
      'Payment Terms': po.paymentTerms || '—',
    });

    doc.moveTo(40, y).lineTo(555, y).strokeColor('#e5e7eb').lineWidth(0.5).stroke();
    y += 15;

    const COLS = [
      { text: '#', x: 40, width: 25 },
      { text: 'Item', x: 65, width: 160 },
      { text: 'HSN', x: 225, width: 55 },
      { text: 'UOM', x: 280, width: 35 },
      { text: 'Qty', x: 315, width: 40 },
      { text: 'Rate', x: 355, width: 55 },
      { text: 'GST%', x: 410, width: 35 },
      { text: 'Amount', x: 445, width: 110 },
    ];

    y = this.addTableHeader(doc, y, COLS);

    po.items.forEach((item, idx) => {
      if (y > 720) { doc.addPage(); y = 40; }
      y = this.addTableRow(doc, y, [
        { text: String(idx + 1), x: 40, width: 25 },
        { text: item.itemName, x: 65, width: 160 },
        { text: item.hsnCode || '—', x: 225, width: 55 },
        { text: item.uom, x: 280, width: 35 },
        { text: String(item.orderedQty), x: 315, width: 40 },
        { text: `Rs.${item.unitPrice}`, x: 355, width: 55 },
        { text: `${item.taxRate || 0}%`, x: 410, width: 35 },
        { text: fmt(item.totalPrice), x: 445, width: 110 },
      ], idx % 2 === 0);
    });

    y = this.addSummaryBox(doc, y, [
      { label: 'Subtotal', value: fmt(po.subtotal) },
      { label: 'Total Tax', value: fmt(po.totalTax) },
      { label: 'Total Amount', value: fmt(po.totalAmount), bold: true },
    ]);

    if (po.notes) {
      y += 10;
      doc.fontSize(8).font('Helvetica-Bold').fillColor('#374151').text('Notes:', 40, y);
      doc.fontSize(8).font('Helvetica').fillColor('#6b7280').text(po.notes, 40, y + 12, { width: 300 });
    }

    this.addFooter(doc, po.company?.name);
    doc.end();

    return new Promise((resolve) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)));
    });
  }

  async generateArInvoicePdf(id: string, companyId: string): Promise<Buffer> {
    const inv = await this.prisma.arInvoice.findFirst({
      where: { id, companyId },
      include: { company: true },
    });
    if (!inv) throw new NotFoundException('Invoice not found');

    const doc = this.createDoc();
    const chunks: Buffer[] = [];
    doc.on('data', chunk => chunks.push(chunk));

    const fmtDate = (d: any) => d ? new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';
    const fmt = (n: any) => `Rs. ${Number(n || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`;

    let y = this.addHeader(doc, 'TAX INVOICE', inv.invoiceNumber, fmtDate(inv.invoiceDate), inv.company?.name);

    y = this.addTwoCol(doc, y, {
      'Customer': inv.customerName,
      'Invoice Date': fmtDate(inv.invoiceDate),
      'Due Date': fmtDate(inv.dueDate),
    }, {
      'Status': inv.status,
      'Total Amount': fmt(inv.totalAmount),
      'Outstanding': fmt(inv.outstandingAmount),
    });

    doc.moveTo(40, y).lineTo(555, y).strokeColor('#e5e7eb').lineWidth(0.5).stroke();
    y += 15;

    y = this.addSummaryBox(doc, y, [
      { label: 'Subtotal', value: fmt(inv.subtotal) },
      { label: 'GST Amount', value: fmt(inv.totalGst) },
      { label: 'Total', value: fmt(inv.totalAmount), bold: true },
      { label: 'Outstanding', value: fmt(inv.outstandingAmount), bold: true },
    ]);

    this.addFooter(doc, inv.company?.name);
    doc.end();

    return new Promise((resolve) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)));
    });
  }

  async generateDispatchPdf(id: string, companyId: string): Promise<Buffer> {
    const dispatch = await this.prisma.dispatch.findFirst({
      where: { id, companyId },
      include: { company: true },
    });
    if (!dispatch) throw new NotFoundException('Dispatch not found');

    const doc = this.createDoc();
    const chunks: Buffer[] = [];
    doc.on('data', chunk => chunks.push(chunk));

    const fmtDate = (d: any) => d ? new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';

    let y = this.addHeader(doc, 'DELIVERY CHALLAN', dispatch.dispatchNumber, fmtDate(dispatch.dispatchDate), dispatch.company?.name);

    y = this.addTwoCol(doc, y, {
      'Customer': dispatch.customerName,
      'Dispatch Date': fmtDate(dispatch.dispatchDate),
      'Transporter': dispatch.transporterName || '—',
    }, {
      'LR Number': (dispatch as any).lrNumber || '—',
      'Vehicle No': (dispatch as any).vehicleNumber || '—',
      'E-Way Bill': (dispatch as any).ewayBillNumber || '—',
      'Status': dispatch.status,
    });

    if (dispatch.deliveryAddress) {
      doc.fontSize(8).font('Helvetica-Bold').fillColor('#6b7280').text('Delivery Address:', 40, y);
      doc.fontSize(9).font('Helvetica').fillColor('#111827').text(dispatch.deliveryAddress, 40, y + 11, { width: 250 });
      y += 40;
    }

    this.addFooter(doc, dispatch.company?.name);
    doc.end();

    return new Promise((resolve) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)));
    });
  }

  async generateNcrPdf(id: string, companyId: string): Promise<Buffer> {
    const ncr = await this.prisma.ncrRecord.findFirst({
      where: { id, companyId },
      include: { company: true },
    });
    if (!ncr) throw new NotFoundException('NCR not found');

    const doc = this.createDoc();
    const chunks: Buffer[] = [];
    doc.on('data', chunk => chunks.push(chunk));

    const fmtDate = (d: any) => d ? new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';

    let y = this.addHeader(doc, 'NON-CONFORMANCE REPORT', (ncr as any).ncrNumber, fmtDate((ncr as any).detectedDate), (ncr as any).company?.name);

    y = this.addTwoCol(doc, y, {
      'NCR Number': (ncr as any).ncrNumber,
      'Source': (ncr as any).source,
      'Severity': (ncr as any).severity,
    }, {
      'Status': ncr.status,
      'Detected By': ncr.detectedBy || '—',
      'Detected Date': fmtDate(ncr.detectedDate),
    });

    doc.moveTo(40, y).lineTo(555, y).strokeColor('#e5e7eb').lineWidth(0.5).stroke();
    y += 15;

    const fields = [
      { label: 'Description', value: ncr.description },
      { label: 'Item', value: ((ncr.itemCode || '') + ' ' + (ncr.itemName || '')).trim() },
      { label: 'Qty Affected', value: ncr.qtyAffected ? String(ncr.qtyAffected) : '—' },
      { label: 'Disposition', value: ncr.disposition || '—' },
      { label: 'Remarks', value: ncr.remarks || '—' },
      { label: 'Status', value: ncr.status || '—' },
    ];

    fields.forEach(f => {
      if (y > 720) { doc.addPage(); y = 40; }
      doc.fontSize(8).font('Helvetica-Bold').fillColor('#6b7280').text(f.label + ':', 40, y);
      doc.fontSize(9).font('Helvetica').fillColor('#111827').text(f.value || '—', 40, y + 12, { width: 515 });
      y += Math.max(30, doc.heightOfString(f.value || '—', { width: 515 }) + 18);
    });

    this.addFooter(doc, (ncr as any).company?.name);
    doc.end();

    return new Promise((resolve) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)));
    });
  }

  // One PDF per stage result - IQC, Quality Manager, Plant Head, or
  // Final Authority - matching the company's existing Excel check
  // sheet layout: Part Name / S.No. / Category / Parameter /
  // Specification / S1-S5 samples / Remark, plus who reviewed it and
  // why (the mandatory remark on every decision).
  async generateIqcStagePdf(iqcId: string, stageResultId: string, companyId: string): Promise<Buffer> {
    const iqc = await this.prisma.iqcInspection.findFirst({
      where: { id: iqcId, companyId },
      include: {
        company: true,
        grn: { select: { grnNumber: true } },
        template: true,
      },
    });
    if (!iqc) throw new NotFoundException('IQC inspection not found');

    const stageResult = await this.prisma.iqcStageResult.findFirst({
      where: { id: stageResultId, iqcId },
      include: { parameterResults: { include: { parameter: true } } },
    });
    if (!stageResult) throw new NotFoundException('Stage result not found');

    const doc = this.createDoc();
    const chunks: Buffer[] = [];
    doc.on('data', chunk => chunks.push(chunk));

    const fmtDate = (d: any) => d ? new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';
    const template: any = (iqc as any).template;
    const stageLabel = stageResult.stage.replace(/_/g, ' ');

    let y = this.addHeader(doc, template ? `IQC INSPECTION OF ${template.name}` : 'IQC INSPECTION', (iqc as any).iqcNumber, fmtDate(stageResult.reviewedAt), (iqc as any).company?.name);

    y = this.addTwoCol(doc, y, {
      'Lot Quantity': (iqc as any).lotQuantity != null ? String((iqc as any).lotQuantity) : '—',
      'Sample Size': (iqc as any).sampleSize != null ? String((iqc as any).sampleSize) : '—',
      'Supplier': (iqc as any).supplierName || '—',
    }, {
      'MRIR No.': (iqc as any).mrirNo || '—',
      'GRN': (iqc as any).grn?.grnNumber || '—',
      'Doc Code': template?.docCode || '—',
    });

    doc.fontSize(10).font('Helvetica-Bold').fillColor('#1e40af').text(`Stage: ${stageLabel}  —  Outcome: ${stageResult.outcome}`, 40, y);
    y += 20;

    const cols = [
      { text: 'S.No', x: 40, width: 25 },
      { text: 'Category', x: 65, width: 45 },
      { text: 'Parameter', x: 110, width: 90 },
      { text: 'Specification', x: 200, width: 100 },
      { text: 'S1', x: 300, width: 35 },
      { text: 'S2', x: 335, width: 35 },
      { text: 'S3', x: 370, width: 35 },
      { text: 'S4', x: 405, width: 35 },
      { text: 'S5', x: 440, width: 35 },
      { text: 'Remark', x: 475, width: 80 },
    ];
    y = this.addTableHeader(doc, y, cols);

    const results = stageResult.parameterResults as any[];
    results.sort((a, b) => (a.parameter?.sortOrder ?? 0) - (b.parameter?.sortOrder ?? 0));
    results.forEach((pr, idx) => {
      if (y > 700) { doc.addPage(); y = 40; y = this.addTableHeader(doc, y, cols); }
      const p = pr.parameter;
      y = this.addTableRow(doc, y, [
        { text: String(p?.sNo ?? ''), x: 40, width: 25 },
        { text: p?.category || '', x: 65, width: 45 },
        { text: p?.parameterName || '', x: 110, width: 90 },
        { text: p?.specification || '', x: 200, width: 100 },
        { text: pr.s1 || '', x: 300, width: 35 },
        { text: pr.s2 || '', x: 335, width: 35 },
        { text: pr.s3 || '', x: 370, width: 35 },
        { text: pr.s4 || '', x: 405, width: 35 },
        { text: pr.s5 || '', x: 440, width: 35 },
        { text: pr.remark || '', x: 475, width: 80 },
      ], idx % 2 === 1);
    });

    y += 15;
    if (y > 680) { doc.addPage(); y = 40; }
    doc.fontSize(8).font('Helvetica-Bold').fillColor('#6b7280').text('Remarks (why this decision was made):', 40, y);
    doc.fontSize(9).font('Helvetica').fillColor('#111827').text(stageResult.remarks, 40, y + 12, { width: 515 });
    y += Math.max(30, doc.heightOfString(stageResult.remarks, { width: 515 }) + 20);

    if (y > 700) { doc.addPage(); y = 40; }
    doc.fontSize(8).font('Helvetica').fillColor('#6b7280').text(`Reviewed by: ${stageResult.reviewedBy}  |  Date: ${fmtDate(stageResult.reviewedAt)}`, 40, y);

    this.addFooter(doc, (iqc as any).company?.name);
    doc.end();

    return new Promise((resolve) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)));
    });
  }
}
